<?php  /*  error_reporting(0); */
		$file_name = rand(10,10000000).'.pdf';
		header('Content-type: application/pdf');
		//header('Content-Disposition: attachment; filename="downloaded.pdf"');
		header('Content-Disposition: attachment; filename="'.$file_name.'"');
		$constant = $_GET["word"];
		$url2 = 'https://m.blog.naver.com/PostView.nhn?blogId=studycadcam&logNo='.$constant;
 		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url2);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
		$headers = array();
		$headers[] = "Host: m.blog.naver.com";
		$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0";
		$headers[] = "Accept: application/json, text/plain, */*";
		$headers[] = "Accept-Language: en-US,en;q=0.5";
		$headers[] = "Referer: https://m.blog.naver.com/PostList.nhn?blogId=studycadcam&categoryNo=103&listStyle=style3";
		$headers[] = "Connection: keep-alive";
		$headers[] = "Cache-Control: max-age=0";
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		$result = curl_exec($ch);
		if (curl_errno($ch)) {    echo 'Error:' . curl_error($ch); }
		curl_close ($ch);



	$re2 = '/<a href="(.*?)\.pdf/';
	$count2 = preg_match_all($re2, $result, $matches2);
	//echo $count2; $number = "sd";
	//echo '<a href="'.$matches2[1][0].'.pdf" download="renamed.pdf"> Click to download</a>';

     $data_url = $matches2[1][0].'.pdf';
 //$data_url  = urlencode($data_url );
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $data_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "Host: blogattach.naver.net";
$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0";
$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8";
$headers[] = "Accept-Language: en-US,en;q=0.5";
$headers[] = "Connection: keep-alive";
$headers[] = "Upgrade-Insecure-Requests: 1";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo $result ;


?>
	
